### ISSUE TITLE
Naming attribute is not found when starting the pyomo_ns server

### ISSUE THREAD

**Issue by aknaut** [PyUtilib/pyutilib#26]
Starting the pyomo_ns server with Python 3.5.3 I got the following error:

```
Error:   File "c:\anaconda3\envs\py35\lib\site-packages\pyutilib\pyro\nameserver.py", line 19, in start_ns
    Pyro.naming.main(sys.argv[1:])
AttributeError: module 'Pyro4' has no attribute 'naming'
```

I already fixed it locally by adding `import Pyro4.naming` on line 32 in \pyutilib\pyro\util.py . So I guess this should be a quick fix. But maybe this should be done at a different location in the code.

**Comment by ghackebeil** [comment]
I came across this a few months ago and made a similar fix in commit 96d215659f27813d436ce903d7f2be1e495729b5.

A PyUtilib release usually gets generated when Pyomo is released, so this should be in a release relatively soon.
